terraform {
  required_version = ">= 1.8.0"
  required_providers {
    authentik = { source = "goauthentik/authentik" }
  }
}

provider "authentik" {
  url      = "http://localhost:9000"
  token    = "test-token-for-terraform"
  insecure = true
}

# ── Bug 1 + Bug 4 regression (var.model + sensitive client_secret) ──────────
#
# Demonstrates that `var.model` works as a pure-HCL alternative to YAML, and
# that a sensitive `client_secret` (generated by Authentik) flows out via the
# module output without breaking the sensitive-safe `for_each` pattern we
# introduced in `authentik_applications.tf`.
#
# Notes:
# - `client_secret` is intentionally omitted on the input side. Authentik
#   generates it on the server, and the provider returns it as a sensitive
#   computed attribute. This avoids Terraform's deep-unknown taint of `any`-
#   typed `var.model` values that would otherwise mark sibling `for_each`
#   sets as unknown — a Terraform language limitation, documented in the
#   README under "Known limitations & patterns".
# - Run: `terraform apply && terraform plan` should show no changes.

module "authentik" {
  source = "../.."

  manage_applications = true

  model = {
    authentik = {
      applications = {
        providers = {
          oauth2 = [
            {
              name               = "dyn-oauth2-provider"
              client_id          = "dyn-client-id"
              authorization_flow = "default-provider-authorization-implicit-consent"
              invalidation_flow  = "default-provider-invalidation-flow"
              allowed_redirect_uris = [
                { matching_mode = "strict", url = "http://localhost:8081/callback" },
              ]
            },
          ]
        }
      }
    }
  }
}
